# Generated by Django 5.2.11 on 2026-04-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='breif_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
