# Generated by Django 5.2.11 on 2026-04-21 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productmodel_breif_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
